### PR TITLE
Started adding huge mod support

### PR DESCRIPTION
**Pull request by TimGoll**
### Description

started adding huge mod support. Not yet finished, many mods to go. But maybe you want to add all these new textures.
Focused my work on GUIs, not on icons. If you want to rework them, feel free ... psds included

- [x] Tested in-game
- [x] Included Photoshop .psd file

### CODE REVIEW

**Comment by ScottKillen** [comment]
@TimGoll Please sign the [CLA](https://www.clahub.com/agreements/ScottKillen/Nellik-s-HighDef-GUIs) to allow me to incorporate these changes.

**Comment by TimGoll** [comment]
done

**Comment by ScottKillen** [comment]
Thanks!

**Comment by ScottKillen** [comment]
@TimGoll 
Please add your psd files for the work you did on JEI.

Just add another commit.

**Comment by TimGoll** [comment]
I have just copied some stuff out of your GUIs, there's no PSD file.

**Comment by ScottKillen** [comment]
OK. Thanks.

**Comment by ScottKillen** [comment]
The packs are not building correctly. This may take a bit to get released.

**Comment by ScottKillen** [comment]
Working on these...but you only did 1.12 versions and all of the files are not in the right place for the pack to build properly.

**Comment by TimGoll** [comment]
Sorry, but I don't know how to make it the way you need it. 
For me it works this way. Just drop all these Folders into the ZIP. And Done.

**Comment by ScottKillen** [comment]
I'm working on fixing it...but following [these instructions](https://github.com/ScottKillen/Nellik-s-HighDef-GUIs/blob/master/README.md#assembling-this-pack) no longer works.

**Comment by ScottKillen** [comment]
I am rejecting this because this breaks the build and does not follow the [contribution conventions](https://github.com/ScottKillen/Nellik-s-HighDef-GUIs/blob/master/CONTRIBUTING.md#conventions) (eg. not **all** psd files are included and none are in the right places).

Furthermore, only support for MC 1.12 versions of the mods are included. When adding support for a mod, support needs to be added for each version of Minecraft, beginning at 1.71.0 and following.

**Comment by TimGoll** [comment]
Okay, if you don't want it, don't use it

**Comment by TimGoll** [comment]
Am I allowed to publish my own add on on curseforge?

**Comment by ScottKillen** [comment]
@TimGoll I do want it, but I don't have the time to fix it.

You are allowed to publish your own add on. If you derive from the content here, you must follow the terms of the [license](https://github.com/ScottKillen/Nellik-s-HighDef-GUIs/blob/master/LICENSE.MD).

**Comment by TimGoll** [comment]
Okay, I'll look into it.
It's basically okay, if I publish a RP without the stuff you have done and mention, that your pack is needed, too.

**Comment by ScottKillen** [comment]
Yes! If you send me a link, I will link to your pack also.

**Pull request closed without merging**
