### PR TITLE
Cosmetic Armor Reworked GUI

### PR DESCRIPTION
**Pull request by fivestang**
### Description

Hi, I did a quick cut up for cosmetic armor but it looks kinda bad with the default buttons.  I'm afraid anything more than cutting and pasting is beyond my abilities :( I also don't have photoshop, so no psd either :(

*Please include an in-game screenshot of your contribution, if possible.*

- [x] Tested in-game
- [ ] Included Photoshop .psd file

### CODE REVIEW

**Comment by ScottKillen** [comment]
@fivestang Please sing the CLA (see above) for proper credit and I will get these cleaned up and in the pack. Thank you!

**Comment by fivestang** [comment]
CLA signed, and I've added 1.7-1.11 as well. (all tested in-game)  Let me know if you need screenshots, I have them but won't bother to attach unless you want to see them.

**Comment by fivestang** [comment]
I've also added Nutrition for 1.12 only, the 1.10 and 11 are not fully skinnable.  The 1.12 looks a little weird as it's extrapolating the texture from a tiny square. It may look better without the stippling.  The carrot icon is a little wonky, it may look better if it's redone by someone more capable. :)

**Comment by ScottKillen** [comment]
These changes have been manually merged.

**Comment by ScottKillen** [comment]
I did not get the Nutrition additions...but it looks simple enough. I will add them soon.

**Pull request closed without merging**
